---
- name: Check current version.
  command: "{{ git_crypt_path }} --version"
  register: git_crypt_current_version
  changed_when: false
  failed_when: false

- name: Delete existing version if it is different.
  file:
    path: "{{ git_crypt_path }}"
    state: absent
  when: >
    git_crypt_current_version.stdout is defined
    and git_crypt_version not in git_crypt_current_version.stdout
