---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Check current version.
  command: git-crypt --version
  register: git_crypt_current_version
  changed_when: false
  failed_when: false

- block:
  - name: Delete existing version if it is different.
    file:
      path: "{{ item }}"
      state: absent
    become: true
    with_items:
      - "{{ git_crypt_clone_path }}"
      - "{{ git_crypt_path }}"

  - name: Git clone
    git:
      repo: http://github.com/AGWA/git-crypt.git
      dest: "{{ git_crypt_clone_path }}"
      version: "{{ git_crypt_version }}"

  - name: Build
    make:
      chdir: "{{ git_crypt_clone_path }}"

  - name: Install
    make:
      chdir: "{{ git_crypt_clone_path }}"
      target: install
      params:
        PREFIX: "{{ git_crypt_home }}"
    become: true
  when: >
    git_crypt_current_version.msg is defined
    or git_crypt_current_version.stderr is defined
    and git_crypt_version not in git_crypt_current_version.stderr
